### ISSUE TITLE
Really interesting to see RLV means reuseable-landing-vehicle

### ISSUE THREAD

**Issue by randomwangran** [Lysandr/MS_thesis#1]

**Comment by Lysandr** [comment]
I did not write this anywhere.

**Comment by randomwangran** [comment]
https://github.com/Lysandr/MS_thesis/blob/a8895161619ba3e6b16a9d01617e34a2c2742dc2/chapter1.tex#L6

reusable launch vehicles (RLVs)

Sorry, I made a mistake. It's reusable launch not landing.

Aplogize my poor working memory.
